import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "@/components/Wrapper";
import Sidebar from "@/components/Sidebar";
const inter = Inter({ subsets: ["latin"]  });

export const metadata: Metadata = {
  title: "Rag app",
  description: "Generated by create-llama",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body
        className={`gap-5 flex background-gradient items-start min-h-screen w-full scrollbar ${inter.className}`}
      >
        <Wrapper Sidebar={<Sidebar  />}>{children}</Wrapper>
      </body>
    </html>
  );
}
